

essentials:
  chatFormat:
    enabled: true
    prefix: "<"
    suffix: ">"
    commands: 
      setname: enabled
  dynamicMotd:
    enabled: true
    interval: 10
    list:
      - "§aAnother JSPrismarine server!"
      - "§bAnother JSPrismarine server!"
      - "§cAnother JSPrismarine server!"
      - "§gAnother JSPrismarine server!"
  webChat:
    enabled: true
    url: ""
    chatFormat: "|SENDER|: |CONTENT|"
  jspMethods:
    commands:
      method: disabled