

essentials:
  chatFormat:
    enabled: true
    prefix: "<"
    suffix: ">"
    commands: 
      setname: enabled
  dynamicMotd:
    enabled: true
    interval: 10
    list:
      - "§aAnother JSPrismarine server!"
      - "§bAnother JSPrismarine server!"
      - "§cAnother JSPrismarine server!"
      - "§gAnother JSPrismarine server!"
  dynamicPlayerCount:
    enabled: true
    maxPlayers: 20
  economyAPI:
    enabled: true
    deafaultBalance: 0
    commands:
      balance: enabled
      updateBalance: enabled
      pay: enabled
  tpa:
    commands:
      warp: enabled
  webChat:
    enabled: true
    url: ""
    chatFormat: "|SENDER|: |CONTENT|"
  jspMethods:
    commands:
      method: disabled